### ISSUE TITLE
FMT_USE_FLOAT128 set when using x86 qemu on x86_64

### ISSUE THREAD

**Issue by a16bitsysop** [fmtlib/fmt#2969]
When compiling locally using docker and qemu and the alpine CI two tests fail only on x86 (they pass on armhf and armv7)

https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/760512#L404

and 

https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/760512#L497

They both look they are using 128bit on a 32bit platform because FMT_USE_FLOAT128 is being set to true in format.h
https://github.com/fmtlib/fmt/blob/c4ee726532178e556d923372f29163bd206d7732/include/fmt/format.h#L723

**Comment by nekopsykose** [comment]
> They both look they are using 128bit on a 32bit platform because FMT_USE_FLOAT128 is being set to true in format.h  

specifically, the #if checks if `__SIZEOF_FLOAT128__` is defined, and it is defined as 16 on our (alpine) x86 toolchain- looking around this doesn't seem to be invalid at first glance (having 128-bit floats on 32-bit x86), but i don't really know for sure.

**Comment by sergiud** [comment]
On a related note: is there a specific reason why these two checks
https://github.com/fmtlib/fmt/blob/c4ee726532178e556d923372f29163bd206d7732/test/format-test.cc#L102
https://github.com/fmtlib/fmt/blob/c4ee726532178e556d923372f29163bd206d7732/test/format-test.cc#L123
use `__SIZEOF_FLOAT128__` directly instead of `FMT_USE_FLOAT128`?

The reason I'm asking is that I have a Clang based musl toolchain claiming to provide `__float128` support but fails during linking with undefined references, e.g., to `__trunctfdf2` and other symbols. While this is likely not an fmt issue, it is currently impossible to override `__float128` detection.

**Comment by vitaut** [comment]
Additionally there is a FP-related chrono-test failure on Debian: #2975.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/2a1b3ac629bfec51ce70d3c0ebaf28e706754e19. Thanks for reporting.

**Comment by vitaut** [comment]
>  is there a specific reason why these two checks ... use __SIZEOF_FLOAT128__ directly instead of FMT_USE_FLOAT128?

Good catch, thanks. Fixed in https://github.com/fmtlib/fmt/commit/05be7a0764f8fbfbdf9c9750ec54d49fe3d2419f.

**Comment by zhsj** [comment]
> Additionally there is a FP-related chrono-test failure on Debian: #2975:
> 
> ```
> ./test/chrono-test.cc:560: Failure
> Expected equality of these values:
>   "44.000000000000"
>   fmt::format("{:%S}", std::chrono::duration<float, std::pico>( 1.54213895E+26))
>     Which is: "16.437500000000"
> [  FAILED  ] chrono_test.special_durations (0 ms)
> ```

The failure still exists with https://github.com/fmtlib/fmt/commit/2a1b3ac629bfec51ce70d3c0ebaf28e706754e19.

https://buildd.debian.org/status/fetch.php?pkg=fmtlib&arch=i386&ver=9.0.0%2Bds1-2&stamp=1657481678&raw=0

**Comment by xvitaly** [comment]
Fixed on Fedora i686. Thanks.

```
Test project /builddir/build/BUILD/fmt-9.0.0/redhat-linux-build
      Start  1: args-test
      Start  2: assert-test
      Start  3: chrono-test
      Start  4: color-test
      Start  5: core-test
      Start  6: gtest-extra-test
      Start  7: format-test
      Start  8: format-impl-test
      Start  9: ostream-test
      Start 10: compile-test
      Start 11: compile-fp-test
      Start 12: printf-test
      Start 13: ranges-test
      Start 14: scan-test
      Start 15: std-test
      Start 16: unicode-test
      Start 17: xchar-test
      Start 18: enforce-checks-test
      Start 19: posix-mock-test
      Start 20: os-test
 1/20 Test  #1: args-test ........................   Passed    0.02 sec
 2/20 Test  #2: assert-test ......................   Passed    0.02 sec
 3/20 Test  #4: color-test .......................   Passed    0.02 sec
 4/20 Test  #5: core-test ........................   Passed    0.02 sec
 5/20 Test  #6: gtest-extra-test .................   Passed    0.02 sec
 6/20 Test  #9: ostream-test .....................   Passed    0.01 sec
 7/20 Test #10: compile-test .....................   Passed    0.01 sec
 8/20 Test #11: compile-fp-test ..................   Passed    0.01 sec
 9/20 Test #12: printf-test ......................   Passed    0.01 sec
10/20 Test #13: ranges-test ......................   Passed    0.01 sec
11/20 Test #14: scan-test ........................   Passed    0.01 sec
12/20 Test #15: std-test .........................   Passed    0.01 sec
13/20 Test #16: unicode-test .....................   Passed    0.01 sec
14/20 Test #18: enforce-checks-test ..............   Passed    0.01 sec
15/20 Test  #7: format-test ......................   Passed    0.02 sec
16/20 Test #17: xchar-test .......................   Passed    0.01 sec
17/20 Test #19: posix-mock-test ..................   Passed    0.01 sec
18/20 Test #20: os-test ..........................   Passed    0.01 sec
19/20 Test  #8: format-impl-test .................   Passed    0.02 sec
20/20 Test  #3: chrono-test ......................   Passed    0.12 sec
100% tests passed, 0 tests failed out of 20
Total Test time (real) =   0.13 sec
```

**Comment by a16bitsysop** [comment]
Fixed on alpine x86 as well:

```
Test project /builds/a16bitsysop/aports/community/fmt/src/fmt-9.0.0
[193](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L193)      Start  1: args-test
[194](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L194) 1/20 Test  #1: args-test ........................   Passed    0.01 sec
[195](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L195)      Start  2: assert-test
[196](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L196) 2/20 Test  #2: assert-test ......................   Passed    0.01 sec
[197](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L197)      Start  3: chrono-test
[198](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L198) 3/20 Test  #3: chrono-test ......................   Passed    0.28 sec
[199](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L199)      Start  4: color-test
[200](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L200) 4/20 Test  #4: color-test .......................   Passed    0.00 sec
[201](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L201)      Start  5: core-test
[202](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L202) 5/20 Test  #5: core-test ........................   Passed    0.01 sec
[203](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L203)      Start  6: gtest-extra-test
[204](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L204) 6/20 Test  #6: gtest-extra-test .................   Passed    0.01 sec
[205](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L205)      Start  7: format-test
[206](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L206) 7/20 Test  #7: format-test ......................   Passed    0.04 sec
[207](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L207)      Start  8: format-impl-test
[208](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L208) 8/20 Test  #8: format-impl-test .................   Passed    0.05 sec
[209](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L209)      Start  9: ostream-test
[210](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L210) 9/20 Test  #9: ostream-test .....................   Passed    0.01 sec
[211](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L211)      Start 10: compile-test
[212](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L212)10/20 Test #10: compile-test .....................   Passed    0.00 sec
[213](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L213)      Start 11: compile-fp-test
[214](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L214)11/20 Test #11: compile-fp-test ..................   Passed    0.00 sec
[215](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L215)      Start 12: printf-test
[216](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L216)12/20 Test #12: printf-test ......................   Passed    0.01 sec
[217](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L217)      Start 13: ranges-test
[218](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L218)13/20 Test #13: ranges-test ......................   Passed    0.00 sec
[219](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L219)      Start 14: scan-test
[220](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L220)14/20 Test #14: scan-test ........................   Passed    0.01 sec
[221](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L221)      Start 15: std-test
[222](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L222)15/20 Test #15: std-test .........................   Passed    0.00 sec
[223](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L223)      Start 16: unicode-test
[224](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L224)16/20 Test #16: unicode-test .....................   Passed    0.01 sec
[225](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L225)      Start 17: xchar-test
[226](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L226)17/20 Test #17: xchar-test .......................   Passed    0.01 sec
[227](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L227)      Start 18: enforce-checks-test
[228](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L228)18/20 Test #18: enforce-checks-test ..............   Passed    0.00 sec
[229](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L229)      Start 19: posix-mock-test
[230](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L230)19/20 Test #19: posix-mock-test ..................   Passed    0.01 sec
[231](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L231)      Start 20: os-test
[232](https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/765477#L232)20/20 Test #20: os-test ..........................   Passed    0.01 sec
```

**Comment by vitaut** [comment]
Thanks everyone for testing. I'll reopen #2975 to track the chrono-test failure which turned out to be unrelated.
