### ISSUE TITLE
3.0.2 release?

### ISSUE THREAD

**Issue by foonathan** [fmtlib/fmt#506]
There are quite a few fixes on master, should I backport them to 3.0.1 and create another bugfix?

I'll have time after C++Now in around two and a half weeks.

Or maybe look into a 3.1.0? I don't know your plans with that.

**Comment by vitaut** [comment]
A new version would be great and it's probably easier to release a new one from what we have in `master` instead of backporting. This can be either 3.1.0 or even 4.0.0 if there are backward-incompatible changes (which I suspect there are). The last few month were slow in terms of new features because I was mostly focused on the `std` branch, but there was a fair amount of fixes.

Thanks a lot for your work!

**Comment by gabime** [comment]
A new release will be very appreciated by users of spdlog too. Thered are indeed some important fixes reported by spdlog users (like #423)

**Comment by foonathan** [comment]
Good, then I'll start working on 3.1.0/4.0.0 soon.

**Comment by meox** [comment]
any news?

**Comment by foonathan** [comment]
I'll do it next week

**Comment by foonathan** [comment]
@vitaut 

Okay, so I've taken a look at the diff between 3.0.1 and current master; most of the things are bugfixes and minor features, but the following are breaking changes:

* printf family of functions moved to external header (72d51e0b1e79afb5243ec66a4a1feb79894027c7 and 9dbb60c4c8019c0d851ce2e61f99cb5c74696369, mainly)
* API changes in `FormatBuf` (73ca9948fec907e118c973700b34ae96c69791c0). I think this one is really minore)
* The introduction of `format_arg` (f19d8f9655d550234f19c6c1f5a99c7eda798c0e). Can't really evaluate this one, nobody will probably call those functions anyway.
* I'm not sure about the new public `format_system_error` (cc9b051d129f85f4382d29dad42e0f0ac10916fb). I haven't considered changes in `internal` as breaking changes, however I've included that one because of the binary compatibility comment in the source file.

Of those breaking changes, the move of printf justifies a bump to 4.0.0, however I think it would be rather underwhelming in terms of features. If I were you, I'd include the printf.h header in format.h for now, and remove it at some later point allowing a 3.1 release. But this is entirely up to you.

If we go for 4.0.0, I'd also suggest that I backport the bugfixes to a 3.0.2.

**Comment by gabime** [comment]
> If were you, I'd include the printf.h header in format.h for now

Please don't. It would add more compilation times to spdlog users (spdlog doesn't use  printf.h and is header only).

**Comment by vitaut** [comment]
Thanks a lot for looking into it, @foonathan.

I think bumping to 4.0.0 is justified by multiple backward-incompatible ABI changes. BTW have you taken into account changes after 3.0.0 that weren't included in 3.0.1?

> If we go for 4.0.0, I'd also suggest that I backport the bugfixes to a 3.0.2.

That would be great if you have time for this.

**Comment by foonathan** [comment]
I used GitHub to compare the two branches, so it should take these into account. And I do got some commits from before I released it, so it should be fine. Will double-check though.

**Comment by foonathan** [comment]
Okay, I've prepared 3.0.2.

You can view the changes here: https://github.com/fmtlib/fmt/compare/3.0.1...release-3.0
Changelog: https://github.com/fmtlib/fmt/blob/release-3.0/ChangeLog.rst

Let me know if that's okay and give me instruction on how to release it again (you've changed the script or something?).

**Comment by codicodi** [comment]
@foonathan I hoped 3.0.2 would contain Windows DLL fixes from https://github.com/fmtlib/fmt/commit/79f11dbaa7fcb5525f572ea3a9bdec12c0886bc8.

**Comment by foonathan** [comment]
I had a bad merge when I tried adding those, so I just reverted them. I'll include them again.

**Comment by foonathan** [comment]
Done.

**Comment by codicodi** [comment]
Strangely enough, still doesn't seem to work: https://gist.github.com/codicodi/a1dbbe42b5c9e44cb17ac9ced99ee1ce

**Comment by foonathan** [comment]
There's also ad6d78f2a8b294fab16fc78f0249d374bd6a94a5, I'll add it as well.

**Comment by foonathan** [comment]
Should work now.

**Comment by foonathan** [comment]
Ping @vitaut

**Comment by vitaut** [comment]
Thanks @foonathan! Sorry for a slow reply - I've been traveling.

The release script can be run as follows:

```
support/manage.py release <branch>
```
You'll need GitHub access token in the `FMT_TOKEN` environment variable. Let me know if there are any issues with the script.

**Comment by foonathan** [comment]
Okay, 3.0.2 is tagged. Might be able to do 4.0.0 tomorrow, if not I'll have to push it until the week after that again.

**Comment by sirzooro** [comment]
Any update on version 4.0?

**Comment by foonathan** [comment]
Sorry I was busy.

@vitaut Proposed changelog is on release-4.0: https://github.com/fmtlib/fmt/blob/release-4.0/ChangeLog.rst

**Comment by vitaut** [comment]
Awesome, thanks! Looks great at the first glance, I'll take a more detailed look tomorrow.

**Comment by vitaut** [comment]
@foonathan, I've double-checked the changelog for release 4.0 and it looks complete, you are very thorough =). Just made a few trivial changes and added examples. I think it's good to go.

**Comment by vitaut** [comment]
Could you also include #526, #527 and https://github.com/fmtlib/fmt/commit/e8ef103799a7849dd8b6cd14c4c9f57645b4eef8 in 4.0?

**Comment by foonathan** [comment]
Done

**Comment by foonathan** [comment]
Okay, I've published the release.

**Comment by vitaut** [comment]
Thanks a lot, @foonathan!
